version: '3.3'
services:
  node:
    build:
      context: ./docker/node
    command: yarn run build
    user: '${USER_ID}:${GROUP_ID}'
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
  php:
    build:
      context: ./docker/php
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    environment:
      APP_ENV: prod
    volumes:
      - .:/var/www:delegated