name: Deploy on production
on:
  push:
    branches: [master]

jobs:
  init:
    runs-on: [production]
    steps:
      - name: Check directory
        id: check-directory
        continue-on-error: true
        run: |
          cd tchevalleraud-cicd_test
          echo ::set-output name=exist::true
      - name: Update exist project
        if: steps.check-directory.outputs.exist == 'true'
        run: |
          cd tchevalleraud-cicd_test
          git checkout master
          git fetch origin --tags
          git pull
      - name: Deploy new project
        if: steps.check-directory.outputs.exist != 'true'
        run: |
          git clone git@github.com:tchevalleraud/cicd_test.git
          mv cicd_test/ tchevalleraud-cicd_test
      - name: Update environment
        run: |
          cd ./tchevalleraud-cicd_test
          rm .env -f
          touch .env
          echo "APP_ENV=prod" >> .env
          echo "DATABASE_URL=\"sqlite:///%kernel.project_dir%/var/data.db\"" >> .env

  build:
    runs-on: [production]
    needs: [init]
    steps:
      - name: Build docker image
        run: |
          cd tchevalleraud-cicd_test/
          make help
          make docker-build
      - name: Dependencies
        run: |
          cd tchevalleraud-cicd_test/
          make vendor/autoload.php
          make public/assets
  deploy:
    runs-on: [production]
    needs: [build]
    steps:
      - name: Start docker stack
        run: |
          cd tchevalleraud-cicd_test/
          make server-start
          sleep 30